# Generated by Django 5.0.3 on 2024-03-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('referencia', models.CharField(max_length=40)),
                ('tipo_producto', models.CharField(choices=[('Llanta', 'Llanta'), ('Aceite', 'Aceite'), ('Filtro', 'Filtro'), ('Grasa', 'Grasa')], max_length=40)),
                ('precio', models.IntegerField()),
                ('unidades_disponibles', models.IntegerField()),
            ],
        ),
    ]
