# Generated by Django 5.0.3 on 2024-04-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_productos_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.nombreservicio'),
        ),
    ]
