# Generated by Django 5.0.3 on 2024-05-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_nombreservicio_alter_servicio_nombre_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='precio_adicional',
            field=models.IntegerField(default=0),
        ),
    ]
